version: '3'
services:
  db-backup:
    image: mysqldump_backup:latest
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - .env
    volumes:
      - /mnt/sql_backups:/backups